apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-location-service
  name: udaconnect-location-service
spec:
  ports:
  - name: expose-cluster-port-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: udaconnect-location-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-location-service
  name: udaconnect-location-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udaconnect-location-service
  template:
    metadata:
      labels:
        app: udaconnect-location-service
    spec:
      containers:
      - image: wingadium1/udaconnect-location-service:latest
        name: udaconnect-location-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always
